{
	"version": 1733931636,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/baground-sheet0.png",
		"images/fontjudul-sheet0.png",
		"images/startplay-sheet0.png",
		"images/logopplg-sheet0.png",
		"images/logosmk-sheet0.png",
		"images/bghome-sheet0.png",
		"images/penjumlahan-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/box1-sheet0.png",
		"images/jwb2-sheet0.png",
		"images/jwb3-sheet0.png",
		"images/jwb1-sheet0.png",
		"images/judul-sheet0.png",
		"images/home-sheet0.png",
		"images/reload-sheet0.png",
		"images/jawaban1-sheet0.png",
		"images/jawaban2-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/particles.png",
		"images/goojob-sheet0.png",
		"images/backhome-sheet0.png",
		"images/btn_menu-sheet0.png",
		"images/bg-sheet0.png",
		"images/bghome2-sheet0.png",
		"images/buttontambah-sheet0.png",
		"images/butttonkurang-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"media/menu game button click sound effect.ogg",
		"media/correct answer sound effect no copyright.m4a",
		"media/correct answer sound effect no copyright.ogg",
		"media/for cute — childrens music (instrumental music for kids).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}